apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bravo.fullname" . }}
  labels:
    {{- include "bravo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bravo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        {{- include "bravo.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bravo.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "azure"
