apiVersion: v1
kind: Service
metadata:
  name: {{ include "charlie.fullname" . }}
  labels:
    {{- include "charlie.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "charlie.selectorLabels" . | nindent 4 }}
